In [1]:
#dependencies
import re
from bs4 import BeautifulSoup 
from splinter import Browser
import requests
import pandas as pd
from selenium import webdriver 
from selenium.common.exceptions import TimeoutException
from webdriver_manager.chrome import ChromeDriverManager
import json
import time
from tqdm.notebook import tqdm

<h4>Start cells here if {state}_geo file has not been FIPS encoded

In [2]:
fips_check = pd.read_csv("data/state_data/geo/geocoded/geo_nh.csv") #- original geocoded file
fips_check = fips_check.drop(["Unnamed: 0.1"], axis =1) 
fips_check.head() #10912

,Unnamed: 0,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,...,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,SBAOfficeLabel,Loan_Range,job_Range,full_add,Lat,Long
0,555483,3128618805,4/14/21,189,PPP,EASTER SEALS NEW HAMPSHIRE INC,555 Auburn St,Manchester,NH,3103.0,...,Services for the Elderly and Persons with Disa...,999 Other,6241 Individual and Family Services,6241.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,500 or more,"555 Auburn St, Manchester, NH",42.984669,-71.449788
1,555484,5946307005,4/6/20,189,PPP,"NAPOLI PSC SERIES, LLC",5 OVERLOOK DR,AMHERST,NH,3031.0,...,Limited-Service Restaurants,999 Other,7225 Restaurants and Other Eating Places,7225.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,20 to 49,"5 OVERLOOK DR, AMHERST, NH",42.821269,-71.607584
2,555485,3345347110,4/11/20,189,PPP,"EASTERN PROPANE GAS, INC.",28 industrial way,ROCHESTER,NH,3867.0,...,Gasoline Stations with Convenience Stores,999 Other,4471 Gasoline Stations,4471.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,250 to 499,"28 industrial way, ROCHESTER, NH",43.309051,-71.004924
3,555486,8543107003,4/8/20,189,PPP,"THE GRANITE GROUP WHOLESALERS, LLC",6 STORRS ST,CONCORD,NH,3301.0,...,"Household Appliances, Electric Housewares, and...",999 Other,4236 Household Appliances and Electrical and E...,4236.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,500 or more,"6 STORRS ST, CONCORD, NH",43.200551,-71.531315
4,555487,2415809002,5/16/21,189,PPP,"LITTLETON HOSPITAL ASSOCIATION, INC.",600 Saint Johnsbury Rd,Littleton,NH,3561.0,...,General Medical and Surgical Hospitals,999 Other,6221 General Medical and Surgical Hospitals,6221.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,250 to 499,"600 Saint Johnsbury Rd, Littleton, NH",44.317917,-71.825393

In [3]:
columns = ['LoanNumber','full_add', 'Lat', 'Long']
fips_check = fips_check[columns]

In [4]:
fips_check_nan = fips_check[fips_check["Lat"].isnull()] # check to make sure no nulls in coords
fips_check_nan

Empty DataFrame
Columns: [LoanNumber, full_add, Lat, Long]
Index: []

In [5]:
fips_check_notna = fips_check[fips_check["Lat"].notna()] # check to make sure no nulls in coords
fips_check_notna #5078

      LoanNumber                               full_add        Lat       Long
0     3128618805          555 Auburn St, Manchester, NH  42.984669 -71.449788
1     5946307005             5 OVERLOOK DR, AMHERST, NH  42.821269 -71.607584
2     3345347110       28 industrial way, ROCHESTER, NH  43.309051 -71.004924
3     8543107003               6 STORRS ST, CONCORD, NH  43.200551 -71.531315
4     2415809002  600 Saint Johnsbury Rd, Littleton, NH  44.317917 -71.825393
...          ...                                    ...        ...        ...
5073  8327357003      15 INDUSTRIAL PARK DR, BERLIN, NH  44.510365 -71.156578
5074  8453917202     453 CENTRAL AVENUE #107, DOVER, NH  43.197461 -70.873775
5075  8581768304                   114 Mast Rd, Lee, NH  43.135207 -70.988428
5076  9240498803              182 W Main St, Conway, NH  43.976081 -71.132761
5077  9968318308           20 Market St, Manchester, NH  42.990220 -71.463840

[5078 rows x 4 columns]

<h4> Start cells here if partial FIPS already available in {state}_fips_scraped file

In [ ]:
fips_check_scraped = pd.read_csv("data/state_data/geo/geo_fips/NH_fips_scraped.csv") 
fips_check_scraped.head()

In [3]:
columns = ['LoanNumber','full_add', 'Lat', 'Long', 'FIPS_z']
fips_check_scraped = fips_check_scraped[columns]

In [4]:
#pd.set_option('display.float_format', '{:.0f}'.format)

In [ ]:
#Latitude, Longitude, not included
fips_check_scraped_notna = fips_check_scraped[fips_check_scraped["Lat"].notna()] # check to make sure no nulls in coords
fips_check_scraped_notna #40813

In [ ]:
#FIPS not included, of Lat, Long available
fips_check_scraped_null = fips_check_scraped_notna[fips_check_scraped_notna["FIPS_z"].isnull()] # check to make sure no nulls in coords
fips_check_scraped_null #1239

<h4>FIPS Script

In [6]:
#if geocode file
lat = fips_check_notna["Lat"].astype(float).astype(str).to_list()
long = fips_check_notna["Long"].astype(float).astype(str).to_list()

#if FIPS_z file 
#lat = fips_check_scraped_null["Lat"].astype(float).astype(str).to_list()
#long = fips_check_scraped_null["Long"].astype(float).astype(str).to_list()

In [7]:
#before running script, check for any NaN within Lat, Long fields. 
def sleep():
    time.sleep(1)
    
executable_path = {'executable_path': ChromeDriverManager().install()}
driver = Browser('chrome', **executable_path, headless=False)    
url = 'https://geocoding.geo.census.gov/geocoder/geographies/coordinates?form'
driver.visit(url)

not_found = []
geo_id = []

i=0
for i in tqdm(range(len(lat))):
    #while i < len(lat):
        driver.find_by_id('_x_id').clear()
        driver.find_by_id('_y_id').clear()
        driver.find_by_id('_x_id').fill(long[i])
        driver.find_by_id('_y_id').fill(lat[i])
        driver.find_by_id('proceed').click()
        #sleep()
        #html = driver.html
        soup = BeautifulSoup(driver.html, 'html.parser')


        results = soup.find_all('div', id='pl_gov_census_geo_geocoder_domain_GeographyResult')
        for result in results:
            result_text = result.text

            result_digits = re.findall('\d+', result_text)
            startswith = [s for s in result_digits if s.startswith('33')] #NH
            fips_elements =[element for element in startswith if len(element)>=15]
            
            try:
                #print(f"{i},{lat[i]},{long[i]} is {fips_elements}")
                geo_id.append(fips_elements)
            except (KeyError, IndexError):
                print(f"{i},{lat[i]},{long[i]} Not Found")
                notfound.append(i)
                geo_id.append(None)  
            except (TimeoutException):
                driver.navigate.refresh()
    
        #sleep()
        i=i+1

====== WebDriver manager ======
Current google-chrome version is 99.0.4844
Get LATEST chromedriver version for 99.0.4844 google-chrome
Driver [/Users/ciaraspencer/.wdm/drivers/chromedriver/mac64/99.0.4844.51/chromedriver] found in cache

HBox(children=(FloatProgress(value=0.0, max=5078.0), HTML(value='')))

https://iqss.github.io/dss-webscrape/filling-in-web-forms.html

In [8]:
geo_id_list =geo_id

Length Check

In [9]:
print(len(geo_id_list))

5078

Matching FIPS to DataFrame

In [10]:
#for geocode file
fips_fill = fips_check_notna #confirm pair to notna DataFrame
#if FIPS available
#fips_fill = fips_check_scraped_null.iloc[:1239]

In [11]:
fips_fill["FIPS_z"] = geo_id_list
fips_fill

,LoanNumber,full_add,Lat,Long,FIPS_z
0,3128618805,"555 Auburn St, Manchester, NH",42.984669,-71.449788,[330110016002004]
1,5946307005,"5 OVERLOOK DR, AMHERST, NH",42.821269,-71.607584,[330110152003024]
2,3345347110,"28 industrial way, ROCHESTER, NH",43.309051,-71.004924,[330170846001012]
3,8543107003,"6 STORRS ST, CONCORD, NH",43.200551,-71.531315,[330130322002006]
4,2415809002,"600 Saint Johnsbury Rd, Littleton, NH",44.317917,-71.825393,[330099601023039]
...,...,...,...,...,...
5073,8327357003,"15 INDUSTRIAL PARK DR, BERLIN, NH",44.510365,-71.156578,[330079506001009]
5074,8453917202,"453 CENTRAL AVENUE #107, DOVER, NH",43.197461,-70.873775,[330170814002015]
5075,8581768304,"114 Mast Rd, Lee, NH",43.135207,-70.988428,[330170805003003]
5076,9240498803,"182 W Main St, Conway, NH",43.976081,-71.132761,[330039554012002]
5077,9968318308,"20 Market St, Manchester, NH",42.990220,-71.463840,[330112004004013]

Remove brackets

In [12]:
fips_fill['FIPS_z'] = fips_fill['FIPS_z'].str[0]
fips_fill

,LoanNumber,full_add,Lat,Long,FIPS_z
0,3128618805,"555 Auburn St, Manchester, NH",42.984669,-71.449788,330110016002004
1,5946307005,"5 OVERLOOK DR, AMHERST, NH",42.821269,-71.607584,330110152003024
2,3345347110,"28 industrial way, ROCHESTER, NH",43.309051,-71.004924,330170846001012
3,8543107003,"6 STORRS ST, CONCORD, NH",43.200551,-71.531315,330130322002006
4,2415809002,"600 Saint Johnsbury Rd, Littleton, NH",44.317917,-71.825393,330099601023039
...,...,...,...,...,...
5073,8327357003,"15 INDUSTRIAL PARK DR, BERLIN, NH",44.510365,-71.156578,330079506001009
5074,8453917202,"453 CENTRAL AVENUE #107, DOVER, NH",43.197461,-70.873775,330170814002015
5075,8581768304,"114 Mast Rd, Lee, NH",43.135207,-70.988428,330170805003003
5076,9240498803,"182 W Main St, Conway, NH",43.976081,-71.132761,330039554012002
5077,9968318308,"20 Market St, Manchester, NH",42.990220,-71.463840,330112004004013

In [13]:
fips_fill.loc[fips_fill["FIPS_z"].isnull()] #check

,LoanNumber,full_add,Lat,Long,FIPS_z
214,8312947109,"200 Baker Ave 300, Concord, NH",42.460189,-71.384571,NaN
1385,3985607103,"500 US HWY 1 BYPASS, PORTSMOUTH, NH",43.128510,-70.707675,NaN
2692,8223087000,"1815 Rt 3, COLUMBIA, NH",40.857830,-74.179704,NaN

Parse for Merge

In [14]:
cols= ["LoanNumber", "FIPS_z"]
fips_fill_parsed = fips_fill[cols]
fips_fill_parsed

      LoanNumber           FIPS_z
0     3128618805  330110016002004
1     5946307005  330110152003024
2     3345347110  330170846001012
3     8543107003  330130322002006
4     2415809002  330099601023039
...          ...              ...
5073  8327357003  330079506001009
5074  8453917202  330170814002015
5075  8581768304  330170805003003
5076  9240498803  330039554012002
5077  9968318308  330112004004013

[5078 rows x 2 columns]

Read in base data

In [15]:
#if from geocode file
fips_check = pd.read_csv("data/state_data/geo/geocoded/geo_nh.csv")
#fips_check = fips_check.drop(["Unnamed: 0.1", "Unnamed: 0.1.1"], axis =1) 
fips_check

#if from FIPS file
#fips_check = pd.read_csv("data/state_data/geo/geo_fips/NH_fips_scraped.csv") 
#fips_check = fips_check.drop(["Unnamed: 0.1", "Unnamed: 0.1.1", "Unnamed: 0"], axis =1) 
#fips_check.head() #15796

,Unnamed: 0,Unnamed: 0.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,...,LongName,TRIIndustrySector,IndustrySubsector,4DigitNAICS,SBAOfficeLabel,Loan_Range,job_Range,full_add,Lat,Long
0,555483,555483,3128618805,4/14/21,189,PPP,EASTER SEALS NEW HAMPSHIRE INC,555 Auburn St,Manchester,NH,...,Services for the Elderly and Persons with Disa...,999 Other,6241 Individual and Family Services,6241.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,500 or more,"555 Auburn St, Manchester, NH",42.984669,-71.449788
1,555484,555484,5946307005,4/6/20,189,PPP,"NAPOLI PSC SERIES, LLC",5 OVERLOOK DR,AMHERST,NH,...,Limited-Service Restaurants,999 Other,7225 Restaurants and Other Eating Places,7225.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,20 to 49,"5 OVERLOOK DR, AMHERST, NH",42.821269,-71.607584
2,555485,555485,3345347110,4/11/20,189,PPP,"EASTERN PROPANE GAS, INC.",28 industrial way,ROCHESTER,NH,...,Gasoline Stations with Convenience Stores,999 Other,4471 Gasoline Stations,4471.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,250 to 499,"28 industrial way, ROCHESTER, NH",43.309051,-71.004924
3,555486,555486,8543107003,4/8/20,189,PPP,"THE GRANITE GROUP WHOLESALERS, LLC",6 STORRS ST,CONCORD,NH,...,"Household Appliances, Electric Housewares, and...",999 Other,4236 Household Appliances and Electrical and E...,4236.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,500 or more,"6 STORRS ST, CONCORD, NH",43.200551,-71.531315
4,555487,555487,2415809002,5/16/21,189,PPP,"LITTLETON HOSPITAL ASSOCIATION, INC.",600 Saint Johnsbury Rd,Littleton,NH,...,General Medical and Surgical Hospitals,999 Other,6221 General Medical and Surgical Hospitals,6221.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,250 to 499,"600 Saint Johnsbury Rd, Littleton, NH",44.317917,-71.825393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5073,560556,560556,8327357003,4/8/20,189,PPP,MOUNTAIN TIRE CORP,15 INDUSTRIAL PARK DR,BERLIN,NH,...,All Other Automotive Repair and Maintenance,999 Other,8111 Automotive Repair and Maintenance,8111.0,NEW HAMPSHIRE DISTRICT OFFICE,"a $150,000-350,000",10 to 19,"15 INDUSTRIAL PARK DR, BERLIN, NH",44.510365,-71.156578
5074,560557,560557,8453917202,4/28/20,189,PPP,EASTERN SPECIALTY CONCRETE INC.,453 CENTRAL AVENUE #107,DOVER,NH,...,Poured Concrete Foundation and Structure Contr...,999 Other,"2381 Foundation, Structure, and Building Exter...",2381.0,NEW HAMPSHIRE DISTRICT OFFICE,"a $150,000-350,000",10 to 19,"453 CENTRAL AVENUE #107, DOVER, NH",43.197461,-70.873775
5075,560558,560558,8581768304,1/29/21,189,PPS,LIVE AND LEARN EARLY LEARNING CENTER,114 Mast Rd,Lee,NH,...,Child Day Care Services,999 Other,6244 Child Day Care Services,6244.0,NEW HAMPSHIRE DISTRICT OFFICE,"a $150,000-350,000",20 to 49,"114 Mast Rd, Lee, NH",43.135207,-70.988428
5076,560559,560559,9240498803,4/23/21,189,PPP,CHILDREN UNLIMITED INC.,182 W Main St,Conway,NH,...,Child and Youth Services,999 Other,6241 Individual and Family Services,6241.0,NEW HAMPSHIRE DISTRICT OFFICE,"a $150,000-350,000",20 to 49,"182 W Main St, Conway, NH",43.976081,-71.132761
5077,560560,560560,9968318308,1/31/21,189,PPS,TRIVANTUS INC.,20 Market St,Manchester,NH,...,Payroll Services,999 Other,"5412 Accounting, Tax Preparation, Bookkeeping,...",5412.0,NEW HAMPSHIRE DISTRICT OFFICE,"a $150,000-350,000",20 to 49,"20 Market St, Manchester, NH",42.990220,-71.463840

Merge with MainFrame

In [16]:
fips_merge = fips_check.merge(fips_fill_parsed, on="LoanNumber", how="left")
fips_merge

,Unnamed: 0,Unnamed: 0.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,...,TRIIndustrySector,IndustrySubsector,4DigitNAICS,SBAOfficeLabel,Loan_Range,job_Range,full_add,Lat,Long,FIPS_z
0,555483,555483,3128618805,4/14/21,189,PPP,EASTER SEALS NEW HAMPSHIRE INC,555 Auburn St,Manchester,NH,...,999 Other,6241 Individual and Family Services,6241.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,500 or more,"555 Auburn St, Manchester, NH",42.984669,-71.449788,330110016002004
1,555484,555484,5946307005,4/6/20,189,PPP,"NAPOLI PSC SERIES, LLC",5 OVERLOOK DR,AMHERST,NH,...,999 Other,7225 Restaurants and Other Eating Places,7225.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,20 to 49,"5 OVERLOOK DR, AMHERST, NH",42.821269,-71.607584,330110152003024
2,555485,555485,3345347110,4/11/20,189,PPP,"EASTERN PROPANE GAS, INC.",28 industrial way,ROCHESTER,NH,...,999 Other,4471 Gasoline Stations,4471.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,250 to 499,"28 industrial way, ROCHESTER, NH",43.309051,-71.004924,330170846001012
3,555486,555486,8543107003,4/8/20,189,PPP,"THE GRANITE GROUP WHOLESALERS, LLC",6 STORRS ST,CONCORD,NH,...,999 Other,4236 Household Appliances and Electrical and E...,4236.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,500 or more,"6 STORRS ST, CONCORD, NH",43.200551,-71.531315,330130322002006
4,555487,555487,2415809002,5/16/21,189,PPP,"LITTLETON HOSPITAL ASSOCIATION, INC.",600 Saint Johnsbury Rd,Littleton,NH,...,999 Other,6221 General Medical and Surgical Hospitals,6221.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,250 to 499,"600 Saint Johnsbury Rd, Littleton, NH",44.317917,-71.825393,330099601023039
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5073,560556,560556,8327357003,4/8/20,189,PPP,MOUNTAIN TIRE CORP,15 INDUSTRIAL PARK DR,BERLIN,NH,...,999 Other,8111 Automotive Repair and Maintenance,8111.0,NEW HAMPSHIRE DISTRICT OFFICE,"a $150,000-350,000",10 to 19,"15 INDUSTRIAL PARK DR, BERLIN, NH",44.510365,-71.156578,330079506001009
5074,560557,560557,8453917202,4/28/20,189,PPP,EASTERN SPECIALTY CONCRETE INC.,453 CENTRAL AVENUE #107,DOVER,NH,...,999 Other,"2381 Foundation, Structure, and Building Exter...",2381.0,NEW HAMPSHIRE DISTRICT OFFICE,"a $150,000-350,000",10 to 19,"453 CENTRAL AVENUE #107, DOVER, NH",43.197461,-70.873775,330170814002015
5075,560558,560558,8581768304,1/29/21,189,PPS,LIVE AND LEARN EARLY LEARNING CENTER,114 Mast Rd,Lee,NH,...,999 Other,6244 Child Day Care Services,6244.0,NEW HAMPSHIRE DISTRICT OFFICE,"a $150,000-350,000",20 to 49,"114 Mast Rd, Lee, NH",43.135207,-70.988428,330170805003003
5076,560559,560559,9240498803,4/23/21,189,PPP,CHILDREN UNLIMITED INC.,182 W Main St,Conway,NH,...,999 Other,6241 Individual and Family Services,6241.0,NEW HAMPSHIRE DISTRICT OFFICE,"a $150,000-350,000",20 to 49,"182 W Main St, Conway, NH",43.976081,-71.132761,330039554012002
5077,560560,560560,9968318308,1/31/21,189,PPS,TRIVANTUS INC.,20 Market St,Manchester,NH,...,999 Other,"5412 Accounting, Tax Preparation, Bookkeeping,...",5412.0,NEW HAMPSHIRE DISTRICT OFFICE,"a $150,000-350,000",20 to 49,"20 Market St, Manchester, NH",42.990220,-71.463840,330112004004013

If FIPS Encoded

In [ ]:
fips_merge["FIPS_z"] = fips_merge["FIPS_z_y"].fillna(fips_merge["FIPS_z_x"])
fips_merge

Drop Extra FIPS Columns

In [ ]:
fips_merge_drop = fips_merge.drop(["FIPS_z_x", "FIPS_z_y"], axis=1)
fips_merge_drop

In [20]:
fips_merge.loc[fips_merge["FIPS_z"].isnull()] #31

,Unnamed: 0,Unnamed: 0.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,...,TRIIndustrySector,IndustrySubsector,4DigitNAICS,SBAOfficeLabel,Loan_Range,job_Range,full_add,Lat,Long,FIPS_z
1457,187081,187081,1004577101,4/9/20,156,PPP,VISION FINANCIAL MARKETS LLC,120 Long Ridge Road 3 North,STAMFORD,CT,...,999 Other,5231 Securities and Commodity Contracts Interm...,5231.0,CONNECTICUT DISTRICT OFFICE,"b $350,000-1 million",50 to 99,"120 Long Ridge Road 3 North, STAMFORD, CT",41.195893,-73.620851,NaN
3075,188699,188699,7637387710,5/1/20,156,PPP,PIONEER EDUCATION LLC,5200 Rte 42,Turnersville,CT,...,999 Other,6116 Other Schools and Instruction,6116.0,CONNECTICUT DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"5200 Rte 42, Turnersville, CT",39.765211,-75.048383,NaN
5247,190871,190871,3539977109,4/11/20,156,PPP,EM BENSON LLC,1486 highland ave building 2 unit 1,CHESHIRE,CT,...,332 Fabricated Metal Products,3329 Other Fabricated Metal Product Manufacturing,3329.0,CONNECTICUT DISTRICT OFFICE,"b $350,000-1 million",10 to 19,"1486 highland ave building 2 unit 1, CHESHIRE, CT",NaN,NaN,NaN
10902,196526,196526,4931747305,4/30/20,156,PPP,ELANUS CAPITAL MANAGEMENT LLC,180 Varick Street,SALISBURY,CT,...,999 Other,5239 Other Financial Investment Activities,5239.0,CONNECTICUT DISTRICT OFFICE,"a $150,000-350,000",5 to 9,"180 Varick Street, SALISBURY, CT",40.727398,-74.005178,NaN

In [17]:
geo_NH_fips = fips_merge

Convert to File

In [18]:
geo_NH_fips.to_csv("data/state_data/geo/geo_fips/NH_fips_scraped.csv")

Review & Compare

In [19]:
geo_NH_fips = pd.read_csv("data/state_data/geo/geo_fips/NH_fips_scraped.csv") 
geo_NH_fips

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,...,TRIIndustrySector,IndustrySubsector,4DigitNAICS,SBAOfficeLabel,Loan_Range,job_Range,full_add,Lat,Long,FIPS_z
0,0,555483,555483,3128618805,4/14/21,189,PPP,EASTER SEALS NEW HAMPSHIRE INC,555 Auburn St,Manchester,...,999 Other,6241 Individual and Family Services,6241.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,500 or more,"555 Auburn St, Manchester, NH",42.984669,-71.449788,3.301100e+14
1,1,555484,555484,5946307005,4/6/20,189,PPP,"NAPOLI PSC SERIES, LLC",5 OVERLOOK DR,AMHERST,...,999 Other,7225 Restaurants and Other Eating Places,7225.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,20 to 49,"5 OVERLOOK DR, AMHERST, NH",42.821269,-71.607584,3.301102e+14
2,2,555485,555485,3345347110,4/11/20,189,PPP,"EASTERN PROPANE GAS, INC.",28 industrial way,ROCHESTER,...,999 Other,4471 Gasoline Stations,4471.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,250 to 499,"28 industrial way, ROCHESTER, NH",43.309051,-71.004924,3.301708e+14
3,3,555486,555486,8543107003,4/8/20,189,PPP,"THE GRANITE GROUP WHOLESALERS, LLC",6 STORRS ST,CONCORD,...,999 Other,4236 Household Appliances and Electrical and E...,4236.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,500 or more,"6 STORRS ST, CONCORD, NH",43.200551,-71.531315,3.301303e+14
4,4,555487,555487,2415809002,5/16/21,189,PPP,"LITTLETON HOSPITAL ASSOCIATION, INC.",600 Saint Johnsbury Rd,Littleton,...,999 Other,6221 General Medical and Surgical Hospitals,6221.0,NEW HAMPSHIRE DISTRICT OFFICE,e $5-10 million,250 to 499,"600 Saint Johnsbury Rd, Littleton, NH",44.317917,-71.825393,3.300996e+14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5073,5073,560556,560556,8327357003,4/8/20,189,PPP,MOUNTAIN TIRE CORP,15 INDUSTRIAL PARK DR,BERLIN,...,999 Other,8111 Automotive Repair and Maintenance,8111.0,NEW HAMPSHIRE DISTRICT OFFICE,"a $150,000-350,000",10 to 19,"15 INDUSTRIAL PARK DR, BERLIN, NH",44.510365,-71.156578,3.300795e+14
5074,5074,560557,560557,8453917202,4/28/20,189,PPP,EASTERN SPECIALTY CONCRETE INC.,453 CENTRAL AVENUE #107,DOVER,...,999 Other,"2381 Foundation, Structure, and Building Exter...",2381.0,NEW HAMPSHIRE DISTRICT OFFICE,"a $150,000-350,000",10 to 19,"453 CENTRAL AVENUE #107, DOVER, NH",43.197461,-70.873775,3.301708e+14
5075,5075,560558,560558,8581768304,1/29/21,189,PPS,LIVE AND LEARN EARLY LEARNING CENTER,114 Mast Rd,Lee,...,999 Other,6244 Child Day Care Services,6244.0,NEW HAMPSHIRE DISTRICT OFFICE,"a $150,000-350,000",20 to 49,"114 Mast Rd, Lee, NH",43.135207,-70.988428,3.301708e+14
5076,5076,560559,560559,9240498803,4/23/21,189,PPP,CHILDREN UNLIMITED INC.,182 W Main St,Conway,...,999 Other,6241 Individual and Family Services,6241.0,NEW HAMPSHIRE DISTRICT OFFICE,"a $150,000-350,000",20 to 49,"182 W Main St, Conway, NH",43.976081,-71.132761,3.300396e+14
5077,5077,560560,560560,9968318308,1/31/21,189,PPS,TRIVANTUS INC.,20 Market St,Manchester,...,999 Other,"5412 Accounting, Tax Preparation, Bookkeeping,...",5412.0,NEW HAMPSHIRE DISTRICT OFFICE,"a $150,000-350,000",20 to 49,"20 Market St, Manchester, NH",42.990220,-71.463840,3.301120e+14

In [20]:
#fill in missing Lat, Long, FIPS
geo_NH_fips.loc[geo_NH_fips["FIPS_z"].isnull()] #1241

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,...,TRIIndustrySector,IndustrySubsector,4DigitNAICS,SBAOfficeLabel,Loan_Range,job_Range,full_add,Lat,Long,FIPS_z
214,214,555697,555697,8312947109,4/15/20,189,PPP,NEW HORIZON COMMUNICATIONS CORP,200 Baker Ave 300,Concord,...,999 Other,5179 Other Telecommunications,5179.0,NEW HAMPSHIRE DISTRICT OFFICE,c $1-2 million,50 to 99,"200 Baker Ave 300, Concord, NH",42.460189,-71.384571,NaN
1385,1385,556868,556868,3985607103,4/12/20,189,PPP,COAST BUICK GMC CADILLAC INC,500 US HWY 1 BYPASS,PORTSMOUTH,...,999 Other,4411 Automobile Dealers,4411.0,NEW HAMPSHIRE DISTRICT OFFICE,"b $350,000-1 million",20 to 49,"500 US HWY 1 BYPASS, PORTSMOUTH, NH",43.128510,-70.707675,NaN
2692,2692,558175,558175,8223087000,4/8/20,189,PPP,HMI ACQUISITION LLC,1815 Rt 3,COLUMBIA,...,999 Other,1153 Support Activities for Forestry,1153.0,NEW HAMPSHIRE DISTRICT OFFICE,"a $150,000-350,000",20 to 49,"1815 Rt 3, COLUMBIA, NH",40.857830,-74.179704,NaN